
services:

  lms:
    image: sixeyed/logitech-media-server:v8.0.0
    build:
      context: ./logitech-media-server

  kubectl:
    image: sixeyed/kubectl:1.21.0
    build:
      args:
        KUBECTL_VERSION: 1.21.0-r0
      context: ./kubectl